[package]
name = "rusty_jisho"
version = "0.1.0"
authors = ["Ari Paasonen <paasar@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { vesrion = "0.10.4", features = ["blocking", "json"] }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
