[package]
name = "rusty_jisho"
version = "0.1.0"
authors = ["Ari Paasonen <paasar@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.15"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
